[package]
name = "zeppelinrust"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = { version = "0.5.1", features = ["json"]}
reqwest = { version ="0.12.9", features=["json"] }
lru_time_cache = "0.11.11"